version: '3.8'
services:
  accept-btco:
    image: "bitcoinnanolabs/accept-btco"
    restart: "unless-stopped"
    ports:
     - "8080:8080"
    volumes:
     - accept-btco:/opt/data
  btco-node:
    image: "bitcoinnanolabs/btco"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - "7076:7076"
    volumes:
     - btco:/root


volumes:
  btco: {}
  accept-btco: {}